# Generated by Django 3.2.7 on 2021-10-11 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubRepos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='name', max_length=200, null=True)),
                ('project_landing', models.ImageField(blank=True, null=True, upload_to='Project_images/')),
                ('about', models.TextField()),
                ('project_link', models.URLField(max_length=250)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'skills',
            },
        ),
        migrations.CreateModel(
            name='Myself',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('about', models.TextField()),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/')),
                ('email', models.EmailField(max_length=254)),
                ('edit_date', models.DateTimeField(auto_now_add=True)),
                ('repos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miscellany.githubrepos')),
                ('skills', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miscellany.skills')),
            ],
            options={
                'db_table': 'myself',
            },
        ),
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('company_name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('skills', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miscellany.skills', verbose_name='Which of my skills are you interested in?')),
            ],
            options={
                'db_table': 'contact_me',
            },
        ),
    ]
