# Generated by Django 3.2.7 on 2021-10-11 03:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miscellany', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GithubRepos',
            new_name='GithubRepo',
        ),
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
